# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-28 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dxfmodel',
            name='file_path',
            field=models.CharField(max_length=512),
        ),
    ]
