# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-29 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0002_auto_20170828_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dxfmodel',
            name='file_path',
        ),
        migrations.AddField(
            model_name='dxfmodel',
            name='uploads',
            field=models.FileField(default=1, upload_to='dxf_files/'),
            preserve_default=False,
        ),
    ]
