# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0003_auto_20170829_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='dxfmodel',
            name='material_guid',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
