# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0005_auto_20170830_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='dxfmodel',
            name='material_code',
            field=models.CharField(max_length=18, null=True, verbose_name='\u6750\u6599\u7f16\u7801'),
        ),
        migrations.AddField(
            model_name='dxfmodel',
            name='material_name',
            field=models.CharField(max_length=256, null=True, verbose_name='\u6750\u6599\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='dxfmodel',
            name='name',
            field=models.CharField(max_length=128, verbose_name='\u6a21\u578b\u540d\u5b57'),
        ),
    ]
