# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0006_auto_20170911_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='dxfmodel',
            name='rotation',
            field=models.BooleanField(default=False, verbose_name='\u65cb\u8f6c'),
        ),
    ]
