# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0007_dxfmodel_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dxfmodel',
            name='shape_num',
            field=models.IntegerField(null=True, verbose_name='\u5305\u542b\u56fe\u5f62'),
        ),
        migrations.AlterField(
            model_name='dxfmodel',
            name='rotation',
            field=models.BooleanField(verbose_name='\u53ef\u65cb\u8f6c'),
        ),
    ]
