# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-12 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0008_auto_20170911_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('material_guid', models.CharField(max_length=128)),
                ('material_name', models.CharField(max_length=256, null=True, verbose_name='\u6750\u6599\u540d\u79f0')),
                ('material_code', models.CharField(max_length=18, null=True, verbose_name='\u6750\u6599\u7f16\u7801')),
                ('unit', models.CharField(max_length=10)),
                ('total_price', models.FloatField(verbose_name='\u7528\u6599\u603b\u4ef7')),
                ('pic_path', models.CharField(max_length=64)),
                ('dxf_models', models.CharField(max_length=256, verbose_name='dxf_ID')),
                ('use_width', models.FloatField(verbose_name='\u4f7f\u7528\u957f\u5ea6')),
                ('price', models.FloatField(verbose_name='\u5355\u4ef7')),
                ('width', models.FloatField(verbose_name='\u6750\u6599\u5bbd\u5ea6')),
                ('areas', models.FloatField(verbose_name='\u7528\u6599\u9762\u79ef')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data_input', models.TextField(null=True)),
                ('comment', models.TextField()),
                ('products', models.ManyToManyField(to='packing.PackDetail')),
            ],
        ),
    ]
